spring:
  application:
    name: delivery-glance
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery_glance}
    username: ${SPRING_DATASOURCE_USERNAME:delivery_glance}
    password: ${SPRING_DATASOURCE_PASSWORD:delivery_glance}
  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
