import { copyTrackingLink, expect, test } from './support/journey'
import { moveCourierTo, openCourierPhone, openRecipientPhone, signIn } from './support/devices'
import { courierMarker, handoffMarker, mapShowingCourier } from './support/recipient'
import { COURIER, COURIER_AT_PICKUP, COURIER_EN_ROUTE, DISPATCHER, HANDOFF, reference } from './support/team'
import {
  confirmHandoff,
  confirmPickup,
  createDelivery,
  directAssign,
  goOnDuty,
  returnToWorkspace,
  startSharing,
} from './support/workspace'

/**
 * The whole product, once, with all three people present.
 *
 * This is the portfolio claim rendered as a test: a Dispatcher creates and assigns, a Courier picks
 * up, shares and delivers, and a Recipient follows it through a Tracking Link without an account.
 * It runs against the Compose image because `/track` is generated by the server and loads a built
 * bundle, so a Recipient journey against the dev server would be exercising a page nobody receives.
 *
 * The Recipient's phone is opened once and never reloaded. Every change it shows after that arrives
 * because the page fetched a fresh snapshot on its own, which is the only way this file can tell
 * live updates apart from a well-timed refresh.
 */
test('a Delivery is created, assigned, carried and followed to handoff', async ({
  page,
  browser,
  dispatcher,
}) => {
  const deliveryReference = reference('happy')

  await test.step('the Dispatcher signs in and creates the Delivery', async () => {
    await signIn(page, DISPATCHER)
  })

  const deliveryId = await createDelivery(page, deliveryReference)

  const courierPhone = await openCourierPhone(browser, COURIER_AT_PICKUP)
  const recipientPhone = await openRecipientPhone(browser)

  try {
    await test.step('the Courier goes on duty and starts sharing', async () => {
      await signIn(courierPhone.page, COURIER)
      await goOnDuty(courierPhone.page)
      await startSharing(courierPhone.page)
    })

    await test.step('the Recipient opens the link before anyone is assigned', async () => {
      const link = await copyTrackingLink(dispatcher, deliveryId)
      await recipientPhone.page.goto(link.url)

      // The token was in the fragment, and the page is required to have spent it and removed it
      // before rendering anything — including from history, so Back cannot walk into a URL that
      // still carries a capability.
      await expect(recipientPhone.page).toHaveURL((url) => url.hash === '')
      await expect(
        recipientPhone.page.getByRole('heading', { name: 'We’re preparing your delivery' }),
      ).toBeVisible()
      await expect(recipientPhone.page.getByText(deliveryReference)).toBeVisible()
      await expect(recipientPhone.page.getByText(HANDOFF.addressLabel)).toBeVisible()
      // Nothing true can be said about a Courier yet, so nothing is said.
      await expect(recipientPhone.page.getByRole('heading', { name: 'Courier', exact: true })).toBeHidden()
      await expect(recipientPhone.page.getByText('Updating automatically')).toBeVisible()
    })

    await test.step('the Dispatcher assigns the nearest Courier', async () => {
      await page.goto(`/deliveries/${deliveryId}`)
      await directAssign(page, COURIER.displayName)
      await expect(page.getByText(COURIER.displayName)).toBeVisible()
      // The recommendation is a distance, never a position. If a coordinate ever reaches this page
      // the Courier's location has left the module that is supposed to own it.
      await expect(page.locator('body')).not.toContainText(String(COURIER_AT_PICKUP.latitude))
    })

    await test.step('the Recipient page notices the Courier by itself', async () => {
      await expect(
        recipientPhone.page.getByRole('heading', { name: 'A courier has been assigned' }),
      ).toBeVisible()
      await expect(recipientPhone.page.getByText(COURIER.displayName)).toBeVisible()
      // A Courier heading to a pickup is not information about this Delivery's journey, and drawing
      // it would put the pickup address on screen by inference.
      await expect(recipientPhone.page.getByRole('heading', { name: 'Courier location' })).toBeHidden()
    })

    await test.step('the Courier confirms pickup and the Recipient sees the location', async () => {
      await returnToWorkspace(courierPhone.page)
      await expect(courierPhone.page.getByText(deliveryReference)).toBeVisible()
      await startSharing(courierPhone.page)
      await confirmPickup(courierPhone.page)

      await expect(
        recipientPhone.page.getByRole('heading', { name: 'Your delivery is on the way' }),
      ).toBeVisible()
      await expect(recipientPhone.page.getByRole('heading', { name: 'Courier location' })).toBeVisible()
      await expect(recipientPhone.page.getByText(/^Live location — updated/)).toBeVisible()
      await expect(recipientPhone.page.getByText(/accurate to about \d+ metres/)).toBeVisible()
      // The map itself, mounted inside the bundled application's Content-Security-Policy. Nothing
      // else in the suite reaches MapLibre: its module is imported only when a map is drawn, and it
      // is drawn only In Transit.
      await expect(mapShowingCourier(recipientPhone.page)).toBeVisible()
      await expect(courierMarker(recipientPhone.page)).toBeVisible()
      await expect(handoffMarker(recipientPhone.page)).toBeVisible()
    })

    await test.step('the Courier moves and the reading stays live', async () => {
      await moveCourierTo(courierPhone, COURIER_EN_ROUTE)
      await expect(courierPhone.page.getByText(/^Live — measured/)).toBeVisible()
      await expect(recipientPhone.page.getByText(/^Live location — updated/)).toBeVisible()
    })

    await test.step('the Courier confirms handoff and the Recipient loses every trace of them', async () => {
      await confirmHandoff(courierPhone.page)

      await expect(recipientPhone.page.getByRole('heading', { name: 'Delivered' })).toBeVisible()
      await expect(recipientPhone.page.getByText(/Handed over at/)).toBeVisible()
      // The Reference and the Handoff Address survive; the Courier and their position do not.
      await expect(recipientPhone.page.getByText(deliveryReference)).toBeVisible()
      await expect(recipientPhone.page.getByText(HANDOFF.addressLabel)).toBeVisible()
      await expect(recipientPhone.page.getByText(COURIER.displayName)).toBeHidden()
      await expect(recipientPhone.page.getByRole('heading', { name: 'Courier location' })).toBeHidden()
    })

    await test.step('the Dispatcher history records all four states', async () => {
      await page.goto(`/deliveries/${deliveryId}`)
      const history = page.getByRole('list').filter({ hasText: 'Awaiting courier' })
      await expect(history).toContainText('Awaiting courier')
      await expect(history).toContainText('Assigned')
      await expect(history).toContainText('In transit')
      await expect(history).toContainText('Delivered')
      await expect(history).toContainText(DISPATCHER.displayName)
      await expect(history).toContainText(COURIER.displayName)
    })
  } finally {
    await courierPhone.context.close()
    await recipientPhone.context.close()
  }
})
