import { defineConfig, devices } from '@playwright/test'

/**
 * The two cross-role journeys, run against the production-like Compose image rather than the dev
 * server. That is deliberate: `/track` is generated by the backend and loads a build artefact, so a
 * Recipient journey against Vite would be testing a page no Recipient ever receives.
 *
 * Start the target first — `docker compose up --build --wait` from the repository root — and the
 * global setup below will say so plainly if it is not answering.
 */
const baseURL = process.env.E2E_BASE_URL ?? 'http://localhost:8080'

export default defineConfig({
  testDir: './e2e',
  // The screenshot capture lives beside the journeys because it drives the product the same way and
  // reuses their fixtures, but it is a different errand: it writes files into `docs/` that get
  // committed. `npm run screenshots` sets DG_SCREENSHOTS and names the file; nothing else runs it.
  testIgnore: process.env.DG_SCREENSHOTS === undefined ? ['**/screenshots.spec.ts'] : [],
  // The Delivery Team is two pre-provisioned accounts, and the one Courier may hold one Active
  // Delivery at a time. Journeys in parallel would queue behind that single account and fail on a
  // race in the harness rather than in the product — and the product's real race is already proved
  // by AssignmentConcurrencyTest, against the database constraint that decides it.
  fullyParallel: false,
  workers: 1,
  // No retries, here or in CI. These journeys exist to be evidence for a claim about the product,
  // and a suite that passes on the second attempt is evidence of nothing.
  retries: 0,
  forbidOnly: process.env.CI !== undefined,
  timeout: 90_000,
  expect: { timeout: 15_000 },
  globalSetup: './e2e/support/globalSetup.ts',
  reporter: [['list'], ['html', { outputFolder: 'playwright-report', open: 'never' }]],
  outputDir: 'test-results',
  use: {
    baseURL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    // Pinned because the product renders instants in the reader's own zone and locale — Core has no
    // time-zone lookup for the Handoff Address, which INCIDENTAL-FINDINGS records as a known gap.
    // Without these two lines a test asserting on a rendered time would be asserting on the machine
    // it happened to run on.
    locale: 'en-GB',
    timezoneId: 'UTC',
  },
  projects: [
    {
      // The Dispatcher's surface, and the harness default. The Courier and the Recipient open their
      // own contexts at their own viewports inside a journey, because a journey is several people
      // at once and only one of them is at a desk.
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
})
