/// <reference types="vitest/config" />
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  // MapLibre asks for a module worker before falling back to a classic one, so its worker bundle
  // has to be modules rather than the IIFE a build would otherwise produce.
  worker: {
    format: 'es',
  },
  build: {
    rollupOptions: {
      input: {
        // The internal application, which Vite serves through index.html as usual.
        index: fileURLToPath(new URL('index.html', import.meta.url)),
        // The Recipient application. It has no HTML of its own: /track is generated by the server,
        // and its inlined bootstrap injects this bundle only once a token exchange has succeeded.
        'track-app': fileURLToPath(new URL('src/track/main.tsx', import.meta.url)),
      },
      output: {
        // Everything else keeps its content hash. This one entry cannot have one, because the
        // bootstrap is a static file that has to name it before any build has happened. Its
        // shared chunks and its lazily loaded map are still hashed; only the door is fixed.
        entryFileNames: (chunk) => (chunk.name === 'track-app' ? '[name].js' : 'assets/[name]-[hash].js'),
      },
    },
  },
  server: {
    proxy: {
      '/api': 'http://localhost:8080',
      '/actuator': 'http://localhost:8080',
    },
    fs: {
      // The /track bootstrap has exactly one copy and it lives beside the server that inlines it,
      // so its test has to read across the web/server boundary. Nothing is newly exposed: that file
      // is the script every visitor of /track already receives inline.
      allow: ['.', '../server/src/main/resources/tracking'],
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/setupTests.ts'],
  },
})
